# Generated by Django 4.2.9 on 2024-02-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='شماره همراه'),
        ),
    ]
