# Generated by Django 4.2.9 on 2024-02-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_otprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprequest',
            options={'verbose_name': 'اطلاعات ورود کاربر', 'verbose_name_plural': 'اطلاعات ورود کاربران '},
        ),
    ]
