# Generated by Django 4.2.9 on 2024-02-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_otprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRequest',
        ),
    ]
