# Generated by Django 4.2.9 on 2024-02-06 23:20

import account_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_otprequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=account_module.models.generate_otp, max_length=4),
        ),
    ]
