# Generated by Django 4.2.9 on 2024-02-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='کاربر فعال/ غیر فعال'),
        ),
    ]
