# Generated by Django 4.2.9 on 2024-02-21 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must start with an alphanumeric character, contain between 3 and 18 of the following: alphanumeric characters, dots, hyphens, or underscores, and end with an alphanumeric character', regex='^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){3,18}[a-zA-Z0-9]$')], verbose_name='نام کاربری'),
        ),
    ]
