# Generated by Django 4.2.9 on 2024-02-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
